main.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/model.go

Summary:
The extension should no longer require a .devxp file in the repo to run.
If ~/.local/devxp/config.yml exists, that file is used.
Issue ID(s): TDX-494
Testing:
- Test Command: make test
Documentation:
- No updates

Fix settings handling

---

.github/workflows/release.yml
README.md
build_release_version.sh
pkg/cmd/cmd.go
pkg/cmd/test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/lint/lint_test.go
pkg/pr/pr.go
pkg/pr/pr_test.go
pkg/test/test.go
pkg/test/test_test.go
pkg/utils/files.go

This PR adds a new command ("gh dxp test") that will look for one of four possible files and run a test command based on these. If no command is found, it will proceed. If a command is found, but returns an error, it will fail. 
The command is also automatically called in the PR flow.
This does _not_ introduce configuration of the test command using the .devxp file
Summary:
- add test command
Testing:
- Test Command: make test
Documentation:
- No updates

Add test command and include in pr flow [minor]

---

.editorconfig
.gitattributes
.github/CODEOWNERS
.github/CONTRIBUTING
.gitignore
.teamcity/settings.kts
CODEOWNERS
Makefile
go.mod
go.sum
pkg/cmd/cmd.go
pkg/cmd/owner.go
pkg/cmd/template.go
pkg/config/config.go
pkg/config/model.go
pkg/owner/owner.go
pkg/owner/owner_test.go
pkg/template/template.go
pkg/template/template_test.go
pkg/test/test.go
pkg/utils/directory.go

Summary:
- Adds codeowners parsing to gh-dxp functionality.
- Updates the project template files. Project template files need to be updated for testing to work.
- Cleared out some linting issues not properly handled as they blocked this commit being clean.
Issue ID(s): TDX-522
Testing:
Documentation:
- No updates

Add codeowners parsing and update template files

---

build_release_version.sh

Summary:
This handles both the lint error prompting the previous change and also (hopefully) a working plugin build
Testing:
Documentation:
- No updates

Save last process exit code as separate variable before evaluating [patch]

---

pkg/cmd/cmd.go
pkg/cmd/pr.go
pkg/pr/model.go
pkg/pr/pr.go
pkg/pr/pr_test.go

This diff adds optional --nounit and --nolint flags to disable tests and linting respectively. If the flags are activated on PR creation (i.e., not update), some "red flags" will be displayed in the PR summary.
Issue ID(s): TDX-530
Testing:
Documentation:
- No updates

add nolint and nounit options to pr flow [minor]

---

pkg/merge/merge.go
pkg/merge/merge_test.go

Summary:
This change removes the --auto from the merge command, as it was causing the dxp merge command to not properly delete the local branch and change back to main if the relevant PR has already been merged in remote.
Issue ID(s): TDX-559
Testing:
Documentation:
- No updates

Delete local branch and change to main also if merge has already been performed in remote [patch]

---

pkg/utils/executor.go

This update attempts to tackle the issue of commands failing and the plugin only printing the exit code by logging stderr in cases where the command exit code is nonzero
Testing:
Documentation:
- No updates

Log stdErr when process exit code is nonzero [patch]

---

pkg/cmd/branch.go
pkg/cmd/lint.go
pkg/cmd/merge.go
pkg/cmd/pr.go
pkg/cmd/status.go
pkg/cmd/test.go
pkg/lint/model.go
pkg/utils/directory.go

Summary:
Originally, this diff was only intended to change the working directory on lint. However, this has interactions with the PR command as well, so I decided to try running pretty much everything from the git root instead. We'll see if it works out.
Testing:
Documentation:
- No updates

Run (almost) all commands from git repo root directory [patch]

---

pkg/cmd/pr.go
pkg/cmd/template.go
pkg/pr/model.go
pkg/pr/pr.go
pkg/pr/pr_test.go

Testing:
Documentation:
- No updates

rename AutoConfirm to TestRun and remove it from command options [patch]

---

pkg/pr/pr.go

This change should've been included in the original feature, probably, as it doesn't make much sense to prompt the user for whether they'd like to create a new commit if they've already specified a commit message
Testing:
Documentation:
- No updates

bypass untracked changes confirmation prompt if commit message option is specified [patch]

---

pkg/prcreate/prcreate_test.go
pkg/utils/directory.go

Summary:
when using 'git mv' to rename files (and perhaps other situations as well), git status will show the file as renamed as opposed to the more usual "old file deleted, new file created". This caused a bug where the pr command was trying to git add a string on the form "oldname.txt -> newname.txt". This change parses these lines so that the new name is included rather than the entire string.
Testing:
Documentation:
- No updates

handle file renames [patch]

---

pkg/test/test.go

Several users have perceived the previous warning as an error, believing that to be the cause of whatever is blocking their commits. This change aims to make it more clear that it is in fact not an error, and also to help them set up testing.
Testing:
Documentation:
- No updates

Make 'no test command found' logging statement a bit more verbose [patch]

---

pkg/cmd/lint.go
pkg/lint/lint.go
pkg/lint/model.go

Because of networking constraints on build agents, one might need to specify a different routing for the image than the default. This adds support for that.
Testing:
Documentation:
- No updates

Allow user to specify a custom linter image [minor]

---

pkg/branch/branch_test.go
pkg/lint/lint.go
pkg/lint/lint_test.go
pkg/pr/prcreate.go
pkg/pr/prcreate_test.go
pkg/pr/prmerge_test.go
pkg/pr/prupdate_test.go
pkg/status/status_test.go
pkg/test/test_test.go
pkg/testutils/mockexecutor.go
pkg/utils/directory.go
pkg/utils/directory_test.go
pkg/utils/executor.go
pkg/utils/files.go
pkg/utils/linuxexecutor.go
pkg/utils/terminal.go

* Add terminal-helper commands to utils
* Added file manipulation function to utils
* Added os.Chdir to the executor, so that it can be mocked
* Made MockExecutor a struct in its own package (testutils). This ensures that we don't need to copy-paste the same MockExecutor to every package. Could use build tags to ensure this does not get built with the regular code, but that breaks VsCode.
* Added specific tests for the utils code. More testing is still needed, though.
* Refactor initiated to support future changes to PR-create/update (where we need the files.go functionality)
* ✅ This PR adds news tests.

Refactor common code in gh-dxp

---

pkg/pr/prcreate.go
pkg/testutils/mockexecutor.go
pkg/testutils/mockexecutor_test.go
pkg/utils/directory_test.go
pkg/utils/files.go
pkg/utils/files_test.go

This change adds automated checks for changes in README and /docs to the PR template.
Created testutils.NewMockExecutor to simplify testing of the documentation, and added tests for that as well.
* ✅ This PR adds news tests.

Add automated documentation checks to PR info

---

pkg/cmd/cmd.go
pkg/cmd/upgrade.go
pkg/upgrade/upgrade.go
pkg/upgrade/upgrade_test.go
pkg/utils/version.go
pkg/utils/version_test.go

This diff contains two changes:
1) Add the gh dxp upgrade command, which will upgrade the extension to the latest version.
2) Add prerun check to all commands, and log a warning if the currently installed version is not equal to the latest version.

Add upgrade command [minor]

---

pkg/cmd/pr.go
pkg/pr/model.go
pkg/pr/pr.go
pkg/pr/prcreate.go
pkg/pr/prupdate.go
pkg/pr/prupdate_test.go

This PR (unfortunately) does a couple of things
* Refactor/move some common code between pr create and pr update
* Perform existing PR check earlier in the pr update flow
* Add persistentflags to pr command and let subcommands inherit.

enable relevant flags in update by setting them as persistentflags in the root pr command [patch]

---

pkg/cmd/cmd.go
pkg/cmd/upgrade.go

As I suspected, trying to 'hot-upgrade' the plugin using the plugin was triggering an error. This hides the upgrade command and changes the suggesed 'your version is outdated' comman

Hide the upgrade command and change the outdated version prompt [patch]

---

pkg/utils/linuxexecutor.go

When running the branch command, checking whether the chosen branch already exists is done by potentially triggering an error. Our current setup of logging stdout/stderr if subcommands return non-zero exit codes is thus triggered any time the branch does not exist, resulting in an empty error line being logged. If we end up with more of this case in the future, where the stderr is not empty, we may consider writing a different function for situations where we expect an error to ignore.

Only log error in executor if output is not empty [patch]

---

pkg/lint/lint_test.go

Since the main required behaviour of the lint command is to call mega-linter-runner with the correct arguments, we need to AssertExpectations (i.e. check that all mocks have been run). This didn't mesh well with creating test cases in a for loop as we've done elsewhere, because it was leading to lots of logic and conditional mocking. This diff refactors the tests into separate functions.
* ✅ This PR adds news tests.

Refactor lint_test.go

---

pkg/template/template.go
pkg/template/template_test.go

Revert the SECURITY.md change.
A SECURITY.md is now located in the elhub/.github repository. This security file is
default for all Elhub projects. Rather than having to maintain individual files in
each repository, it is better to just use this central version.

Remove SECURITY.md

---

pkg/pr/prcreate.go
pkg/utils/spinner.go
pkg/utils/spinner_test.go

The current spinner implementation has been unable to handle the situation where the underlying call fails in an elegant manner, leading to users reporting that they'll get conflicting messages such as "PR updated" while also seeing stderr output from an obviously failed command.
This diff seeks to remedy this by preventing the success message from being output if the underlying operation fails.
* ✅ This PR adds new tests.

Add ability to remove spinner final message [patch]

---

pkg/pr/pr.go
pkg/pr/prmerge.go
pkg/pr/prmerge_test.go

Some users have reported that when merging pr's the resulting commit message is the first commit message of the branch, and not the PR title as is intended. This is default behaviour in GitHub.
This change aims to ensure that the pr merge command will always use the PR title and body, even if there is only one commit in the branch.

Enforce use of pr title and body in squash commit message when merging

---

pkg/pr/pr.go
pkg/pr/prcreate.go
pkg/pr/prmerge.go
pkg/status/status.go
pkg/testutils/mockexecutor.go
pkg/testutils/mockexecutor_test.go
pkg/utils/executor.go
pkg/utils/linuxexecutor.go
pkg/utils/version.go

The Executor interface has been somewhat inconsistent in its signature. When using the Command method, the return type has been (string, error) - while GH has had (byte.buffer, error). Furthermore, the codebase has been seeing an increasing number of lines simply casting the byte buffer to a string upon reception, prompting me to change the return type to string for consistency and chillness.

Refactor executor GH return type from byte.buffer to string [patch]

---

.github/CONTRIBUTING.md
.gitignore
alias.yml
docs/command-reference.md
pkg/cmd/cmd.go
pkg/cmd/repo.go
pkg/repo/model.go
pkg/repo/repo.go
pkg/repo/repo_test.go
pkg/utils/directory.go

This adds a new clone-all command. Due to issues we have noted with the API,
this does not try to parallelize clones; everything is done sequentially to keep
things simple.
Currently this grabs everything that the user has access to. An --owner or--organization
option should probably be introduced to allow the user to limit which organization
repos are cloned.
* ✅ This PR adds new tests.

Add clone-all functionality to gh-dxp

---

pkg/cmd/repo.go
pkg/repo/repo.go
pkg/repo/repo_test.go

When cloning all or most of the repos in the Elhub org, several users have reported getting 'connection reset' error messages for some of the repos. This could be some kind of throttling by github - necessitating rerunning the script at least once to get all the repos.
This diff introduces a one second delay to each clone, which does seem to prevent this issue _on my machine_ but also slows the total clone time down by a lot.
**EDIT: I've replaced the delay with some retry logic that seems to do the trick**

Introduce retry logic to clone operation

---

pkg/lint/lint.go
pkg/lint/lint_test.go
pkg/pr/prcreate_test.go
pkg/pr/prupdate_test.go

A common grievance with this extension is that running the lint command spams the user's repository with several lint configuration files. This change sets the configuration variable LINTER_RULES_PATH to /tmp, which presumably spams the /tmp directory of the container instead

Set linter rules path to /tmp

---

README.md
pkg/lint/lint_test.go
pkg/pr/prcreate_test.go
pkg/utils/files.go

This is needed to resolve an issue where the main branch is not present on newly created teamcity agents
* ⛔ **This PR has not been unit tested! The --notest option was used.**
* ✅ Documentation Updates: README

fix: add step to check out main if it does not exist
