elhub/gh-dxp

- .github/workflows/release.yml
- build_release_version.sh
Testing:
Documentation:
- No updates
> Add automatic release [patch]

- pkg/lint/lint.go
- pkg/lint/lint_test.go
- pkg/utils/files.go
Testing:
- Test Command: make test
Documentation:
- No updates
> Add functionality for config-free linting

- pkg/pr/pr.go
- pkg/pr/pr_test.go
Testing:
Documentation:
- No updates
> Add tracked file handling [minor]

- .teamcity/pom.xml
- .teamcity/settings.kts
Issue ID(s): TDX-469
Testing:
- Test Command: make test
Documentation:
- No updates
> Update TC settings

- .teamcity/pom.xml
- .teamcity/settings.kts
Testing:
Documentation:
- No updates
> Add go to local settings

- .teamcity/pom.xml
- .teamcity/settings.kts
Testing:
Documentation:
- No updates
> Fix the path of the environment

- .teamcity/settings.kts
Summary:
- Test local GO params
Testing:
Documentation:
- No updates
> Add more path variables

- .teamcity/pom.xml
- .teamcity/settings.kts
- Makefile
- pkg/test/test.go
- pkg/test/test_test.go
Summary:
The default test target for Makefile is check, not test. This change fixes that.
Testing:
Documentation:
- No updates
> Add correct support for make

- alias.yml
Summary:
- Add alias specification
Testing:
- Test Command: gh alias import alias.yml
Documentation:
- No updates
> Add gh aliases

- pkg/owner/owner.go
- pkg/test/test.go
- pkg/utils/directory.go
Issue ID(s): TDX-538
Testing:
Documentation:
- No updates
> Use filepath.Join when joining paths [patch]

- pkg/pr/pr.go
- pkg/pr/pr_test.go
Summary:
- Revert "Revert "remove request for test command in pr flow [patch]""
- Revert "remove request for test command in pr flow [patch]"
- remove request for test command in pr flow [patch]
🚩🚩🚩 **This PR has not been linted!**
Testing:
Documentation:
- No updates
> Remove query for test command in pr flow [patch]

- pkg/utils/executor.go
🚩🚩🚩 **This PR has not been linted!**
Testing:
Documentation:
- No updates
> Add debugging statements to commandcontext and gh functions in executor [patch]

- pkg/pr/pr.go
- pkg/pr/pr_test.go
Summary:
- pass commitMessage directly instead of doing interpolation [minor]
- fix test related to git add
Testing:
Documentation:
- No updates
> remove quotes from commit messages [patch]

- pkg/cmd/merge.go
- pkg/cmd/pr.go
- pkg/utils/directory.go
Testing:
Documentation:
- No updates
> Enforce working directory to be in a GitHub repository in commands that use gh cli (pr,merge) [patch]

- pkg/branch/branch.go
- pkg/pr/pr.go
- pkg/pr/pr_test.go
Testing:
Documentation:
- No updates
> Add functionality to automatically create a branch if pr command is run from base branch [minor]

- .github/workflows/release.yml
- .gitignore
- pkg/cmd/lint.go
- pkg/lint/lint.go
- pkg/lint/lint_test.go
- pkg/lint/model.go
Testing:
Documentation:
- No updates
> Add fix flag to lint [minor]

- README.md
Testing:
Documentation:
- README.md
> Move some documentation

- pkg/cmd/pr.go
- pkg/pr/model.go
- pkg/pr/pr.go
Testing:
Documentation:
- No updates
> Add cli options to pr command [minor]

- README.md
Testing:
Documentation:
- README.md
> add reference to docs-support

- .teamcity/settings.kts
🚩🚩🚩 **This PR has not been linted!**
Testing:
Documentation:
- No updates
> Remove releaseVersion from pipeline

- .teamcity/pom.xml
🚩🚩🚩 **This PR has not been linted!**
Testing:
Documentation:
- No updates
> Update build configuration version

- pkg/prcreate/prcreate.go
Testing:
Documentation:
- No updates
> Only log info about branch option being ignored if we're not on main, AND the branch option is a different branch from the current one [patch]

- pkg/cmd/test.go
- pkg/pr/model.go
- pkg/pr/prcreate.go
- pkg/pr/prcreate_test.go
- pkg/pr/prupdate.go
- pkg/test/test.go
- pkg/test/test_test.go
This fixes the test message in the PR body when no tests exist to be run.
> Fix test message when no tests exist

- pkg/pr/prcreate.go
> Fix description appearing as a heading without any text in section

- pkg/pr/prmerge.go
* ⛔ **This PR has not been linted! The --nolint option was used.**
* ⛔ **This PR has not been unit tested! The --notest option was used.**
> general kenobi

- .github/CONTRIBUTING
- .gitignore
- pkg/pr/prmerge.go
* Revert "general kenobi (#91)"
> run template command and revert demo pr

- docs/command-reference.md
> Add command reference docs

- Makefile
> print total test coverage in make check

- README.md
* ✅ Documentation Updates: README
> remove roadmap section of readme

- pkg/cmd/pr.go
- pkg/pr/model.go
- pkg/pr/prcreate.go
- pkg/pr/prcreate_test.go
> Add issues to prc options [minor]

- pkg/pr/prcreate.go
> fix typo in pr template

- pkg/template/template.go
- pkg/template/template_test.go
* Add SECURITY.md to the template setup.
* Correct CONTRIBUTING to also have a markdown extension.
* ✅ This PR adds news tests.
> Add security.md to templates

- pkg/template/template.go
- pkg/template/template_test.go
This file will in future be served from [.github](https://gitbug.com/elhub/.github)
> Remove CONTRIBUTING.md from templates

- .editorconfig
- pkg/pr/prlist_ui.go
> Set pr list column width to fixed size

- pkg/cmd/template.go
- pkg/template/model.go
- pkg/template/template.go
- pkg/template/template_test.go
> feat: add gradle option to template cmd

- main.go
- pkg/branch/branch.go
- pkg/cmd/alias.go
- pkg/cmd/cmd.go
- pkg/lint/lint.go
- pkg/logger/logger.go
- pkg/pr/pr.go
- pkg/pr/prcreate.go
- pkg/pr/prmerge.go
- pkg/repo/repo.go
- pkg/status/status.go
- pkg/test/test.go
- pkg/utils/linuxexecutor.go
This diff introduces the logger package, which wraps the existing logging library in order to enable yellow warning text and red error text. Another approach that I did consider was to replace the existing logging library entirely, seeing as this one is clearly quite limited. I decided against it for now, on account of this approach being relatively straightforward. If more complex logging needs should occur in the future, one should very seriously consider switching to a more fully featured logging library.
> Make log message levels more visually distinct

- .teamcity/pom.xml
- .teamcity/settings.kts
> Add lint to pipeline

- .devxp/compass.yaml
> Add compass configuration

- .github/renovate.json
> Enable Renovate scanning for gh-dxp

- .editorconfig
- .teamcity/pom.xml
- .teamcity/settings.kts
> chore: update teamcity settings

- pkg/lint/lint_test.go
- pkg/pr/prcreate_test.go
- pkg/pr/prupdate_test.go
- pkg/utils/files.go
- pkg/utils/files_test.go
Locally update origin/HEAD symbolic reference to point at the default branch
* ✅ This PR adds new tests.
> Update origin/HEAD symbolic reference

- .gitattributes
- .gitignore
> chore: run gh dxp template

- .editorconfig
- pkg/lint/lint_test.go
- pkg/pr/prupdate_test.go
- pkg/utils/files.go
- pkg/utils/files_test.go
> fix: add step to update main before performing file comparison

- pkg/lint/lint_test.go
- pkg/pr/prcreate_test.go
- pkg/pr/prupdate_test.go
- pkg/utils/files.go
- pkg/utils/files_test.go
> fix: explicitly compare to origin/main

- pkg/utils/files.go
> Add logs for debugging

- .teamcity/settings.kts
> Fix sonar params

- .teamcity/settings.kts
- Makefile
> Fix TC workingdir

- .teamcity/settings.kts
> Add sourcedirs to Sonar scan

- pkg/config/config.go
- pkg/config/model.go
- pkg/pr/prcreate.go
- pkg/pr/prcreate_test.go
* ⛔ **This PR has not been linted! The --nolint option was used.**
> feat: add jira links to issue ids in prs
